### ISSUE TITLE
Flutter app deamon crashes on ubuntu core with inotifywait error

### ISSUE THREAD

**Issue by KirioXX** [MirServer/iot-example-graphical-snap#30]
Hi,
Thanks for this repository it helped a lot to setup our flutter app snap.

We setup some test devices with Ubuntu Core and our Flutter app and noticed that they after a couple days crash.

In a local env I only seen it a couple of times but I was able to get the logs when one of my devices crashed:
```sh
2024-03-14T18:51:28Z systemd[1]: snap.twa.daemon.service: Main process exited, code=exited, status=1/FAILURE
2024-03-14T18:51:28Z systemd[1]: snap.twa.daemon.service: Failed with result 'exit-code'.
2024-03-14T18:51:31Z systemd[1]: snap.twa.daemon.service: Scheduled restart job, restart counter is at 2.
2024-03-14T18:51:31Z systemd[1]: Stopped Service for snap application twa.daemon.
2024-03-14T18:51:31Z systemd[1]: Started Service for snap application twa.daemon.
2024-03-14T18:51:31Z twa.daemon[9035]: ERROR: inotifywait could not be found, mir-kiosk-snap-launch expects:
2024-03-14T18:51:31Z trunk-works-andon.daemon[9035]:  . . :     stage-packages:
2024-03-14T18:51:31Z trunk-works-andon.daemon[9035]:  . . :        - inotify-tools
2024-03-14T18:51:31Z systemd[1]: snap.twa.daemon.service: Main process exited, code=exited, status=1/FAILURE
2024-03-14T18:51:31Z systemd[1]: snap.twa.daemon.service: Failed with result 'exit-code'.
```

Is there anything in our configuration or our device setup that could cause this behaviour?
Please let me know what else would help to debug this issue.
Thanks!

**Comment by Saviq** [comment]
Hi @KirioXX, as logged you should add this to your snap:

```yaml
stage-packages:
  - inotify-tools
```

To confirm the tool is there: `snap run --shell twa.daemon -c 'which inotifytools'`.

That won't be the reason for your app to crash, though - it wouldn't start in the first place:

https://github.com/canonical/iot-example-graphical-snap/blob/dcf41bf23cbf1c9730c52c121261f4a557b4fca1/wayland-launch/bin/wayland-launch#L11-L17

**Comment by KirioXX** [comment]
Thank you for your answer @Saviq .
We actually have this:
```yaml
stage-packages:
  - inotify-tools
```
part in our configuration.

This is our config:
```yaml
 name: twa
version: 1.12.0
summary: custom ubuntu core snap
description: >
  Custom ubuntu core snap
confinement: strict
compression: lzo
grade: stable
base: core22

apps:
  twa:
    command-chain: &ref_0
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: &ref_1 bin/twa
    plugs: &ref_2
      - opengl
      - wayland
      - network
      - network-observe
      - network-bind
      - network-status
      - network-control
      - network-manager
      - network-manager-observe
      - netlink-audit
      - netlink-connector
      - qualcomm-ipc-router
      - network-setup-observe
      - bluetooth-control
      - avahi-observe
    environment: &ref_3
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *ref_0
    command: *ref_1
    plugs: *ref_2
    environment: *ref_3

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
environment:
  XDG_CACHE_HOME: $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS: $SNAP/usr/local/share:$SNAP/usr/share
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/local/share/fonts:
    bind: $SNAP/usr/local/share/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
  /usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0:
    bind: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /etc/gtk-3.0:
    bind: $SNAP/etc/gtk-3.0

parts:
  gsettings+pixbuf+immodules:
    plugin: nil
    build-packages:
      - libgdk-pixbuf2.0-0
      - librsvg2-common
      - shared-mime-info
      - libgtk-3-0
    override-build: >
      craftctl default
      # Update mime database
      update-mime-database ${CRAFT_PART_INSTALL}/usr/share/mime
      # build immodules cache
      mkdir -p ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0/3.0.0/
      /usr/lib/${CRAFT_ARCH_TRIPLET}/libgtk-3-0/gtk-query-immodules-3.0 > ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0/3.0.0/immodules.cache
    stage-packages:
      - librsvg2-common
      - gsettings-desktop-schemas
      - libglib2.0-bin
    override-prime: >
      craftctl default
      # Compile the gsettings schemas
      /usr/lib/${CRAFT_ARCH_TRIPLET}/glib-2.0/glib-compile-schemas "$CRAFT_PRIME/usr/share/glib-2.0/schemas"
      # Index the pixbuf loaders
      LOADERS_PATH=$(echo ${CRAFT_PRIME}/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/*/loaders)
      QUERY_LOADERS=/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
      GDK_PIXBUF_MODULEDIR=${LOADERS_PATH} ${QUERY_LOADERS} > ${LOADERS_PATH}/../loaders.cache
      sed -i 's!'"$CRAFT_PRIME"'!!g' "${LOADERS_PATH}/../loaders.cache"

  twa:
    plugin: nil
    source: .
    build-snaps:
      - flutter/latest/stable
    build-environment:
      - C_INCLUDE_PATH: /snap/flutter/current/usr/include
      - LD_LIBRARY_PATH: >-
          ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/snap/flutter/current/usr/lib/$CRAFT_ARCH_TRIPLET
      - PKG_CONFIG_PATH: >-
          ${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}/snap/flutter/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - XDG_DATA_DIRS: /snap/flutter/current/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    override-build: >
      set -eux
      echo "Installing flutter"
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      flutter channel stable
      flutter upgrade
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      echo "Removing the build folder"
      rm -Rf build/
      echo "Start building the app"
      flutter build linux --release -v
      echo "Copying the build to the part install folder"
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    stage-packages:
      - libgtk-3-0
      - libgl1

  setup:
    plugin: dump
    source: snap/local/wayland-launch
    override-build: >
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="opengl wayland graphics-core22"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/setup.sh
      craftctl default
    stage-packages:
      - inotify-tools

  graphics-core22:
    after:
      - twa
      - gsettings+pixbuf+immodules
      - setup
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
      cd "$CRAFT_PRIME/usr/share/"
      rm -rf bug drirc.d glvnd libdrm lintian man
      rm -rf applications apport bash-completion dbus-1 doc-base doc gtk-doc\
             help pkgconfig libthai metainfo themes thumbnailers xml
    prime:
      - bin/graphics-core22-wrapper

architectures:
  - build-on: amd64
  - build-on: arm64
```

What I noticed we don't have the hooks because they caused some trouble when we tried to install the snap on Ubuntu Core. Could it be the reason that when it maybe tries to refresh the snap that it crashes because the hook is missing?
